server.port=8080
spring.application.name=FinalProject

spring.datasource.url=jdbc:jdbc:mysql://localhost:3306/librows
spring.datasoource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

